"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var Yup=_interopRequireWildcard(require("yup")),_Glottolog=_interopRequireDefault(require("../../models/Glottolog")),_Location=_interopRequireDefault(require("../../models/Location"));function _interopRequireDefault(a){return a&&a.__esModule?a:{default:a}}function _getRequireWildcardCache(){if("function"!=typeof WeakMap)return null;var a=new WeakMap;return _getRequireWildcardCache=function(){return a},a}function _interopRequireWildcard(a){if(a&&a.__esModule)return a;if(null===a||"object"!=typeof a&&"function"!=typeof a)return{default:a};var b=_getRequireWildcardCache();if(b&&b.has(a))return b.get(a);var c={},d=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var e in a)if(Object.prototype.hasOwnProperty.call(a,e)){var f=d?Object.getOwnPropertyDescriptor(a,e):null;f&&(f.get||f.set)?Object.defineProperty(c,e,f):c[e]=a[e]}return c.default=a,b&&b.set(a,c),c}// Validation Library
// Model
// Validation Schema
const CollectionValidationSchema=Yup.object().shape({name:Yup.string().required("Se requiere ingresar un nombre"),description:Yup.string().required("Se requiere ingresar una descripcion"),languages:Yup.array().of(Yup.string(),"Se requiere un Arreglo de Strings"),localities:Yup.array().of(Yup.string(),"Se requiere un Arreglo de Strings"),license:Yup.string().required("Se requiere ingresar una licencia").oneOf(["CC-BY-NC-SA","CC BY-SA"],"Debe proporcionarse un tipo de licencia valida: CC-BY-NC-SA o CC BY-SA")});var _default=async(a,b,c)=>{// Get Params from req
let{languages:d,localities:e}=a.body;const{name:f,description:g,license:h}=a.body;try{d=d.split("|"),e=e.split("|");// Form collection document
let b={name:f,description:g,languages:d,localities:e,license:h};// Se validan datos del formulario
await CollectionValidationSchema.validate(b,{abortEarly:// error
// error
// error
!1});// Se Buscan los lenguajes
// Get collections
let i=await _Glottolog.default.find({_id:{$in:d}},"gid family_id parent_id name level latitude longitude iso639P3code child_family_count child_language_count child_dialect_count country_ids").exec();if(0==i.length)throw new Yup.ValidationError(`Lenguajes incorrectos`,a.body.languages,"No se proporcionaron lenguajes correctos");// Se puede refactorar y hacer desde el modelo
b.languages=i.map(a=>{let b=a.toJSON();return delete b._id,b});let j=await _Location.default.find({_id:{$in:e}},"Cve_Ent Nom_Ent Nom_Abr Cve_Mun Nom_Mun Cve_Loc Nom_Loc Lat_Decimal Lon_Decimal Altitud").exec();if(0==j.length)throw new Yup.ValidationError(`Localidades Incorrectas`,a.body.localities,"No se proporcionaron localidades correctas");// Se puede refactorar y hacer desde el modelo
b.localities=j.map(a=>{let b=a.toJSON();return delete b._id,b}),a.body.collection=b,c()}catch(c){console.log(`validator>collection> ${c}`),a.flash("error_msg",`Formulario incorrecto: ${c.message}`),b.render("index/dashboard")}};exports.default=_default;