"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var _path=_interopRequireDefault(require("path")),_jsonReader=_interopRequireDefault(require("../helpers/jsonReader")),_User=_interopRequireDefault(require("../models/User")),_Collection=_interopRequireDefault(require("../models/Collection"));function _interopRequireDefault(a){return a&&a.__esModule?a:{default:a}}// DELETE async
const edit=(a,b)=>{let c=_jsonReader.default.readFileSync(_path.default.join(__dirname,"..","assets","languages.json")),d=_jsonReader.default.readFileSync(_path.default.join(__dirname,"..","assets","countries.json")),e="";a.user.spokenLanguages.forEach(a=>{e=e.concat(`${a.name} | ${a.gid}\n`)}),e=e.trim(),b.render("user/edit",{title:"SYLARD Editar Cuenta",spokenLang:e,nativeLanguages:c,countries:d})},editUserById=async(a,b)=>{let c=_jsonReader.default.readFileSync(_path.default.join(__dirname,"..","assets","languages.json")),d=_jsonReader.default.readFileSync(_path.default.join(__dirname,"..","assets","countries.json"));const{userId:e}=a.params;if(e==a.user._id)return b.redirect("/user/edit");try{// Getting user
let a=await _User.default.findById(e),f="";//
a.spokenLanguages.forEach(a=>{f=f.concat(`${a.name} | ${a.gid}\n`)}),f=f.trim(),b.render("user/editById",{title:"SYLARD Editar Cuenta",userToEdit:a.toJSON(),spokenLang:f,nativeLanguages:c,countries:d})}catch(a){b.json({error:a.message})}},postEditUserById=async(a,b)=>{const{name:c,lastName:d,secLastName:e,email:f,spokenLanguages:g,country:h,about:i}=a.body,{userId:j}=a.params;try{let k=await _User.default.findById(j);// Flash Message
// Get the info from
await k.editUser({name:c,lastName:d,secLastName:e,email:f,spokenLanguages:g,country:h,about:i}),a.flash("success_msg","Sus cambios se han guardado"),b.redirect("/user")}catch(a){b.json({error:a.message})}},editUser=async(a,b)=>{// Get values from req.body
const{name:c,lastName:d,secLastName:e,email:f,spokenLanguages:g,country:h,about:i}=a.body;//return res.json({spokenLanguages})
// Update user
// Flash Message
// Get the info from
await a.user.editUser({name:c,lastName:d,secLastName:e,email:f,spokenLanguages:g,country:h,about:i}),a.flash("success_msg","Sus cambios se han guardado"),b.redirect("/dashboard")},editPassword=(a,b)=>{b.render("user/editPassword",{title:"SYLARD Editar contrase\xF1a"})},editUserPassword=async(a,b)=>{const{password:c}=a.body;await a.user.editPassword(c),a.flash("success_msg","Password editado con exito"),b.redirect("/dashboard")},resetPassword=(a,b)=>{b.render("user/resetPassword",{title:"SYLARD Editar Cuenta"})},resetUserPassword=async(a,b)=>{// Se busca usuario con el password
await a.user.resetPassword(),a.flash("success_msg","Su password provisional se ha enviado a su correo"),b.redirect("/")},index=async(a,b)=>{// res.render('user/index', { usersObjs })
const c=await _User.default.find({role:{$ne:"su"}}).lean().exec();/*
  #THESIS
  REF: https://advancedweb.hu/how-to-use-async-functions-with-array-map-in-javascript/#:~:text=The%20map%20function,-The%20map%20is&text=An%20async%20version%20needs%20to,the%20results%20in%20an%20Array.
  */let d=await Promise.all(c.map(async a=>{a.role="colaborator"===a.role?"checked":"";let b=await _Collection.default.find({user:a._id});return a.collectionsDocs=b.map(a=>a.toJSON()),a}));// Buscando las colecciones de este usuario
//let collectionsDoc = Collection.find({"user":})
b.render("user/index",{usersObjs:d})},delUsers=async(a,b)=>{let{usersIds:c}=a.body;// Normalizing
c="string"==typeof c?[c]:c,console.log("========================================================"),console.log("========================================================"),console.log(">>>>>>>>>>>>>>>>>>>>>>> TODO <<<<<<<<<<<<<<<<<<<<<<<<<<<"),console.log("> FALTA QUE SE IMPLEMENTE BORRADO DE AUDIO ANOTACIONES"),console.log("> CUANDO SEBORRAN USUARIOS cotrollers/users.js"),console.log("========================================================"),console.log("========================================================");//
let d={},e={user:{$in:c}};// DELETE USERS COLLECTIONS
try{d=await _Collection.default.find(e,{name:!0}).remove().exec()}catch(a){// Error al borrar audio anotaciones
return b.status(404).json(a)}// Building Query
e={_id:{$in:c}},d={};try{d=await _User.default.find(e,{name:!0,role:!0}).remove().exec(),console.log(JSON.stringify(d)),a.flash("success_msg",`Usuarios borrados con exito: ${d.deletedCount}`)}catch(b){console.log(b),a.flash("error_msg","No se ha podido actualizar la colecci\xF3n")}finally{b.redirect("/user")}},api_toggleUserPrivileges=async(a,b)=>{let{userId:c}=a.params;// Finding User by Id
try{let a=await _User.default.findById(c),d=await a.toggleUserPrivileges();b.status(200).json(d)}catch(a){b.status(500).json({error:a.message})}},api_getUsers=async(a,b)=>{const c=await _User.default.find().exec();b.status(200).json(c)},api_delUsers=async(a,b)=>{let{usersIds:c}=a.body;// Normalizing
c="string"==typeof c?[c]:c;// Building Query
let d={_id:{$in:c}};try{const a=await _User.default.find(d).exec();let c=Promise.all(a.map(async a=>{console.log(`>> Deleting user: ${a.name}`);let b=await a.deleteOne();return b}));b.status(200).json({result:"Dellete user(s) ok",deletionResults:c})}catch(a){console.log(`>-> Error al borrar usuario(s): ${a.message}`),b.status(500).json({error:a.message})}},delById=async(a,b)=>{let{userId:c}=a.params;try{let a=await _User.default.findById(c),d=await a.deleteOne();console.log(`> DELETE: ${d}`),b.redirect("/user")}catch(a){b.status(500).json({error:a.message})}};var _default={edit,editUser,postEditUserById,editUserById,editPassword,editUserPassword,resetPassword,resetUserPassword,index,delUsers,api_getUsers,api_delUsers,api_toggleUserPrivileges,delById};exports.default=_default;